name: RemakePhone
version: '${project.version}'
main: nl.thebathduck.remakephone.RemakePhone
authors: [ TheBathDuck ]
loadbefore:
  - MinetopiaSDB
depend: [ WorldEdit, WorldGuard, Essentials, Vault, GPS, PlaceholderAPI ]
commands:
  remakephone: {}
  huizenmarkt:
    aliases:
      - home
      - huis
  phonereload: {}
  plotinfo:
    aliases:
      - pi